name: http_logger_library
description: A logging middleware for Dart's http module forked from TEDConsulting/http_logger.
homepage: https://github.com/sdugene/http_logger_library
version: 0.12.1

dependencies:
  http_middleware_library: "^0.12.1+hotfix.1"

environment:
  sdk: ">=2.1.0 <3.0.0"
